sudo: required

services:
  - docker

before_install:
  - docker build -t vinay/docker-react -f Dockerfile.dev .

script : 
  - docker run -e CI=true vinay/docker-react npm run test

deploy :
  provider : elasticbeanstalk
  region : "ap-south-1"
  app : docker
  env : "Docker-env"
  bucket : "elasticbeanstalk-ap-south-1-582368090716"
  bucket_path : "docker"
  on : 
    branch : master
  access_key_id : $AWS_ACCESS_KEY
  secret_access_key :
    secure : $AWS_SECRET_KEY